#!/bin/bash

# git repository init script, version 0.1
# (c) Alexander Kharitonov <askh@askh.ru>, 2023

# The reposities directory
REPO_BASE_DIR=/srv/git

# The regular expression for validation the repository name
REPO_NAME_REGEX="^[0-9a-zA-Z]([0-9a-zA-Z._-]*[0-9a-zA-Z_-])?$"

# The maximum length of the repository name
REPO_NAME_MAX_LEN=64

function error_exit()
{
  error_message=$1
  echo "ERROR: $error_message" >&2
  exit 1
}

if (( $# == 0 ))
then
  echo "Use: git-init-bare REPO_NAME"
  echo "REPO_NAME - the repository name without suffix .git"
  exit
fi

repo_name="$1"

repo_name_len=$(echo -n "$repo_name" | wc -c)

if (( $repo_name_len > $REPO_NAME_MAX_LEN ))
then
    error_exit "The repository name is too long."
fi

if ! [[ $repo_name =~ $REPO_NAME_REGEX ]]
then
    error_exit "Incorrect repository name."
fi

repo_full_path="$REPO_BASE_DIR/$repo_name.git"

if [[ -e "$repo_full_path" ]]
then
  error_exit "The directory $repo_full_path exists."
fi

git init --bare "$repo_full_path" || error_exit "Can't create the repository."

echo "The repository $repo_full_path was created successfully."

