#!/bin/bash

REPO_BASE_DIR=/srv/git

function error_exit()
{
  error_message=$1
  echo "ERROR: $error_message" >&2
  exit 1
}

if (( $# == 0 ))
then
  echo "Use: git-init-base REPO_NAME"
  echo "REPO_NAME - the repository name without suffix .git"
  exit
fi

repo_name="$1"

repo_full_path="$REPO_BASE_DIR/$repo_name.git"

if [[ -e "$repo_full_path" ]]
then
  error_exit "The directory $repo_full_path exists."
fi

git init --bare "$repo_full_path" || error_exit "Can't create the repository."

echo "The repository $repo_full_path was created successfully"
